import { Platform, StyleSheet } from 'react-native';
import { font } from './font';
import { FontWeight } from '../../utils/enums';
import {
  actuatedNormalizeModerateScale,
  actuatedNormalizeWidth,
} from '../../utils/utility';

const typography = StyleSheet.create({
  DisplayRegular: {
    fontSize: actuatedNormalizeModerateScale(48),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0),
    lineHeight: actuatedNormalizeModerateScale(68),
    fontWeight: FontWeight._400,
  },
  HeadingRegular1: {
    fontSize: actuatedNormalizeModerateScale(34),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(40),
    fontWeight: FontWeight._400,
  },
  HeadingRegular2: {
    fontSize: actuatedNormalizeModerateScale(24),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0),
    lineHeight: actuatedNormalizeModerateScale(28),
    fontWeight: FontWeight._400,
  },
  HeadingBold3: {
    fontSize: actuatedNormalizeModerateScale(20),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(24),
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
  },
  HeadingBold2: {
    fontSize: actuatedNormalizeModerateScale(18),
    fontFamily: font.MulishBold,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(24),
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
  },
  HeadingBold4: {
    fontSize: actuatedNormalizeModerateScale(18),
    fontFamily: font.MulishBold,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(24),
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
  },

  SubTitleRegular1: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._400,
  },
  SubTitleMedium1: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._500,
  },
  SubTitleBold1: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishSemiBold,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
  },
  SubTitleRegular2: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.1),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._400,
  },
  SubTitleMedium2: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.1),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._500,
  },

  DisplayMedium: {
    fontSize: actuatedNormalizeModerateScale(48),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0),
    lineHeight: actuatedNormalizeModerateScale(68),
    fontWeight: FontWeight._500,
  },
  HeadingMedium1: {
    fontSize: actuatedNormalizeModerateScale(34),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(40),
    fontWeight: FontWeight._500,
  },
  HeadingMedium2: {
    fontSize: actuatedNormalizeModerateScale(24),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0),
    lineHeight: actuatedNormalizeModerateScale(28),
    fontWeight: FontWeight._500,
  },
  HeadingRegular3: {
    fontSize: actuatedNormalizeModerateScale(20),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(24),
    fontWeight: FontWeight._400,
  },

  BodyRegular1: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(actuatedNormalizeWidth(0.5)),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._400,
  },
  BodyRegular2: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._400,
  },
  BodyRegular3: {
    fontSize: actuatedNormalizeModerateScale(12),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._400,
  },
  BodySemiBold1: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishSemiBold,
    letterSpacing: actuatedNormalizeWidth(0.5),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._600,
  },
  BodySemiBold2: {
    fontFamily: font.MulishSemiBold,
    fontSize: actuatedNormalizeModerateScale(14),
    fontWeight: FontWeight._600,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
  },
  BodySemiBold3: {
    fontSize: actuatedNormalizeModerateScale(12),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._600,
  },

  ButtonLarge: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._600,
  },
  ButtonSmall: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._600,
  },
  LinkMedium: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishSemiBold,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
  },
  LinkRegular: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._400,
  },
  LinkSemiBold: {
    fontSize: actuatedNormalizeModerateScale(12),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._600,
  },
  LabelLargeRegular: {
    fontSize: actuatedNormalizeModerateScale(12),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._400,
  },
  LabelLargeMedium: {
    fontSize: actuatedNormalizeModerateScale(12),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
    fontWeight: FontWeight._500,
  },
  LabelSmallRegular: {
    fontSize: actuatedNormalizeModerateScale(10),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(12),
    fontWeight: FontWeight._400,
  },
  LabelSmallMedium: {
    fontSize: actuatedNormalizeModerateScale(10),
    fontFamily: font.MulishMedium,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(12),
    fontWeight: FontWeight._500,
  },
  BadgesLabelStyle: {
    fontSize: actuatedNormalizeModerateScale(9),
    fontFamily: font.MulishRegular,
    fontWeight: FontWeight._500,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(11.3),
  },
  labelSmallSemiBold: {
    fontFamily: font.MulishRegular,
    fontSize: actuatedNormalizeModerateScale(10),
    fontWeight: FontWeight._600,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
  },
  HeadingLabel1: {
    fontSize: actuatedNormalizeModerateScale(10.86),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(13.26),
  },
  HeadingLabel2: {
    fontSize: actuatedNormalizeModerateScale(20.21),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(24.27),
  },
  HeadingLabel3: {
    fontSize: actuatedNormalizeModerateScale(16.07),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(19.62),
  },
  HeadingLabel4: {
    fontSize: actuatedNormalizeModerateScale(55.53),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(50.31),
  },
  HeadingLabel5: {
    fontSize: actuatedNormalizeModerateScale(29.9),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(27.09),
  },
  HeadingLabel6: {
    fontSize: actuatedNormalizeModerateScale(26),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(23.56),
  },
  subHeadingLabel: {
    fontSize: actuatedNormalizeModerateScale(15),
    fontFamily: font.HelveticaNeue,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(12.86),
  },
  ButtonTitle: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.RobotoRegular,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(16),
  },
  ButtonTitleMedium: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.RobotoRegular,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(20),
  },
  ButtonTitleLarge: {
    fontSize: actuatedNormalizeModerateScale(19),
    fontFamily: font.RobotoRegular,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.34),
    lineHeight: actuatedNormalizeModerateScale(22),
  },
  AccordionTitleBold: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    fontWeight: FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(17.57),
  },
  MiniSuccessTitleBold: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily:font.MulishRegular,
    fontWeight:Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(17.57),
  },
  AccordionTitleRegular: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    fontWeight: FontWeight._400,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(17.57),
  },
  OtpInputStyle: {
    fontSize: actuatedNormalizeModerateScale(40),
    fontFamily: font.MulishRegular,
    fontWeight: FontWeight._600,
    letterSpacing: actuatedNormalizeWidth(0.25),
    lineHeight: actuatedNormalizeModerateScale(52),
  },
  miniSuccessPageTitle: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishRegular,
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(20),
  },
  Gcatitle: {
    fontSize: actuatedNormalizeModerateScale(20),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(28),
    fontWeight: Platform.OS === 'android' ? FontWeight._600 : FontWeight._700,
  },
  GcaAlphabetStyle: {
    fontSize: actuatedNormalizeModerateScale(14),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(20),
    fontWeight: FontWeight._600,
  },
  GcaTextInputStyle: {
    fontSize: actuatedNormalizeModerateScale(20),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(32),
    fontWeight: FontWeight._600,
  },
  SliderTitleStyle: {
    fontSize: actuatedNormalizeModerateScale(24),
    fontFamily: font.MulishRegular,
    fontWeight: FontWeight._600,
    letterSpacing: actuatedNormalizeWidth(0.18),
    lineHeight: actuatedNormalizeModerateScale(30.12),
  },
  rupeeTextStyle:{
    fontSize: actuatedNormalizeModerateScale(28),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(36),
    fontWeight: FontWeight._600,
  },
  ToolTipText: {
    fontSize: actuatedNormalizeModerateScale(16),
    fontFamily: font.MulishRegular,
    letterSpacing: actuatedNormalizeWidth(0.15),
    lineHeight: actuatedNormalizeModerateScale(24),
    fontWeight: FontWeight._400,
  },
});

export default typography;
