import { StyleSheet } from 'react-native';

import { colors, typography } from '../../../../atoms';
import {
    actuatedNormalizeHeight,
    actuatedNormalizeModerateScale,
    actuatedNormalizeWidth,
} from '../../../../utils/utility';

const styles = StyleSheet.create({
    backGroundImage1: {
        left: actuatedNormalizeWidth(16),
        height: actuatedNormalizeHeight(41),
        position: 'absolute',
        width: actuatedNormalizeWidth(50)
    },
    backGroundImage2: {
        left: actuatedNormalizeWidth(331),
        height: actuatedNormalizeHeight(41),
        position: 'absolute',
        top: actuatedNormalizeHeight(109),
        width: actuatedNormalizeWidth(50),
    },
    centerIcon: {
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(29),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(58),
        position: 'absolute',
        top: actuatedNormalizeHeight(49),
        width: actuatedNormalizeWidth(58),
    },
    closeIcon:{
        position:'absolute',
        right:actuatedNormalizeWidth(16),
        top:actuatedNormalizeHeight(16),
    },
    leftTopImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        left: actuatedNormalizeWidth(108),
        position: 'absolute',
        top: actuatedNormalizeHeight(31),
        width: actuatedNormalizeWidth(42),
    },
    leftMiddleImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        left: actuatedNormalizeModerateScale(50),
        position: 'absolute',
        top: actuatedNormalizeHeight(51),
        width: actuatedNormalizeWidth(42),
    },
    leftBottomImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        left: actuatedNormalizeWidth(90),
        position: 'absolute',
        top: actuatedNormalizeHeight(94),
        width:actuatedNormalizeWidth(42),
    },
    linearGradientStyle: {
        borderTopLeftRadius: actuatedNormalizeModerateScale(24),
        borderTopRightRadius: actuatedNormalizeModerateScale(24),
        height: actuatedNormalizeHeight(350),
        width: actuatedNormalizeWidth(360),
    },
    modalTouchableStyle: {
        backgroundColor: 'rgba(0,0,0,0.5)',
        flex: 1,
        height: '100%',
    },
    rightTopImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        position: 'absolute',
        right: actuatedNormalizeWidth(96),
        top: actuatedNormalizeHeight(31),
        width: actuatedNormalizeWidth(42),
    },
    rightMiddleImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        position: 'absolute',
        right: actuatedNormalizeWidth(49),
        top: actuatedNormalizeHeight(62),
        width: actuatedNormalizeWidth(42),
    },
    rightBottomImageStyle: {
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: actuatedNormalizeWidth(21),
        justifyContent: 'center',
        height: actuatedNormalizeWidth(42),
        position: 'absolute',
        right: actuatedNormalizeModerateScale(97),
        top: actuatedNormalizeHeight(96),
        width: actuatedNormalizeWidth(42),
    },
    rightButtonStyle: {
        borderRadius: actuatedNormalizeModerateScale(8),
        justifyContent: 'center',
        height: actuatedNormalizeHeight(32),
        position: 'absolute',
        right: actuatedNormalizeWidth(0),
    },
    subTitleStyle: {
        ...typography.SubTitleRegular2,
        color: colors.NeutralGrey110,
        justifyContent: 'center',
        left: actuatedNormalizeWidth(16),
        textAlign: 'center',
        top: actuatedNormalizeHeight(168),
        width: actuatedNormalizeWidth(328),
    },
    textContainer: {
        height: actuatedNormalizeHeight(58),
        width: actuatedNormalizeWidth(328),
        justifyContent: 'center',
        top: actuatedNormalizeHeight(-50),
    },
    textInputStyles: {
        backgroundColor: colors.White,
        borderRadius: 16,
        flex: 1,
        marginHorizontal:actuatedNormalizeWidth(16),
        color:colors.NeutralGrey140
    },
    textInputContainerStyle: {
        alignSelf: 'center',
        backgroundColor:colors.White,
        borderColor: colors.White,
        borderRadius: actuatedNormalizeWidth(16),
        borderWidth: 1,
        elevation: 12,
        justifyContent: 'center',
        height: actuatedNormalizeHeight(48),
        position: 'absolute',
        shadowColor: 'rgba( 0,0,0,0.05)',
        shadowOpacity: 1,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 2 },
        top: actuatedNormalizeHeight(236),
        width: actuatedNormalizeWidth(296),
    },
    titleStyle: {
        ...typography.SubTitleBold1,
        color: colors.NeutralGrey140,
        paddingTop: actuatedNormalizeHeight(4),
        textAlign: 'center',
        top: actuatedNormalizeHeight(158),
    },
    poweredByStyle: {
        ...typography.LinkSemiBold,
        alignSelf: 'center',
        color: colors.NeutralGrey110,
        position: 'absolute',
        textAlign: 'center',
        top: actuatedNormalizeHeight(290),
    },
    upiStyle: {
        alignSelf: 'center',
        position: 'absolute',
        top: actuatedNormalizeHeight(316),
    }

});
export default styles;
