export declare const textDayFontFamily = 'Mulish';
export declare const textMonthFontFamily = 'Mulish-Regular';
export declare const textDayHeaderFontFamily = 'Mulish';
export declare const todayButtonFontFamily = 'Mulish';
export declare const textDayFontWeight = '600';
export declare const textMonthFontWeight = '400';
export declare const textDayHeaderFontWeight: undefined;
export declare const todayButtonFontWeight = '600';
export declare const textDayFontSize = 16;
export declare const textMonthFontSize = 14;
export declare const textDayHeaderFontSize = 13;
export declare const todayButtonFontSize = 14;
export declare const textDayStyle: undefined;
export declare const dotStyle: undefined;
export declare const arrowStyle: undefined;
export declare const calendarBackground = '#F8F9FB';
export declare const textSectionTitleColor = '#b6c1cd';
export declare const textSectionTitleDisabledColor = '#d9e1e8';
export declare const selectedDayBackgroundColor = '#F0792E';
export declare const selectedDayTextColor = 'white';
export declare const todayBackgroundColor: undefined;
export declare const todayTextColor = '#F0792E';
export declare const dayTextColor = '#7D8287';
export declare const textDisabledColor = '#d9e1e8';
export declare const textInactiveColor = '#d9e1e8';
export declare const dotColor = '#00BBF2';
export declare const selectedDotColor = 'white';
export declare const disabledDotColor: undefined;
export declare const inactiveDotColor: undefined;
export declare const todayDotColor: undefined;
export declare const arrowColor = '#00BBF2';
export declare const disabledArrowColor = '#d9e1e8';
export declare const monthTextColor = '#2d4150';
export declare const indicatorColor: undefined;
export declare const agendaDayTextColor = '#7a92a5';
export declare const agendaDayNumColor = '#7a92a5';
export declare const agendaTodayColor = '#00BBF2';
export declare const agendaKnobColor = '#f2F4f5';
export declare const expandableKnobColor = '#e8ecf0';
export declare const backgroundColor = '#EFF1F6';
export declare const reservationsBackgroundColor = '#f2F4f5';
export declare const todayButtonTextColor = '#00BBF2';
export declare const todayButtonPosition: undefined;
export declare const weekVerticalMargin = 7;
