export const STRINGS = {
    str_button_title: 'Send Money',
    str_car_loan: 'FOR A CAR LOAN',
    str_icici_card: 'Get an ICICI Credit Card',
    str_joining_fees: 'JOINING FEES',
    str_loan_account: 'Loan Account',
    str_loan_approval: 'You have a pre-approved offer on a car loan for ₹10L',
    str_message: "Mobile Number Is All You \nNeed To Send Money",
    str_no_documentation_needed: 'No documentation needed!',
    str_open_account_message: 'Open a new ICICI',
    str_portrait: 'Portrait',
    str_pre_approved_loan: 'YOU ARE PRE-APPROVED',
    str_shortCarousel: 'Short Carousel',
    str_square: 'Square',
    str_tall_full_width_carousel: 'Tall Full Width',
    str_tall_story_style: 'Tall Story ',
    str_tallCarousel: 'Tall Carousel',
    str_tallwidth_button_title:'Send now',
    str_title: 'Banners',
    str_zero: 'ZERO',
  };