import { StyleSheet } from 'react-native';

import { colors,typography } from '../../../atoms';
import { actuatedNormalizeWidth,actuatedNormalizeHeight,actuatedNormalizeModerateScale } from '../../../utils/utility';

export default StyleSheet.create({
  containerStyle: {
    alignItems: 'center',
    columnGap:actuatedNormalizeWidth(12),
    flexDirection: 'row',
  },
  containerStyle1: {
    alignItems: 'center',
    columnGap:actuatedNormalizeWidth(4),
    flexDirection: 'row',
  },
  containerStyle2: {
    alignItems: 'center',
    columnGap:actuatedNormalizeWidth(8),
    flexDirection: 'row',
  },
  customIconContainerStyle: {
    flex: 1,
    rowGap:actuatedNormalizeModerateScale(12)
  },
  customIconMultiSubContainer1: {
    alignItems: 'center',
    columnGap:actuatedNormalizeWidth(12),
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  customIconMultiSubContainer2: {
    alignItems: 'center',
    columnGap:actuatedNormalizeWidth(12),
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  defaultContainerStyle: {
    backgroundColor: colors.LightGrayishOrangeWithOpacity40,
    borderRadius: actuatedNormalizeModerateScale(12),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(64),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(8),
    width:actuatedNormalizeWidth(328),  
  },
  defaultContainerStyle2: {
    backgroundColor: colors.LightGrayishOrangeWithOpacity40,
    borderRadius: actuatedNormalizeModerateScale(12),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight:actuatedNormalizeHeight(76),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(12), 
    width:actuatedNormalizeWidth(328),
  },
  defaultContainerStyle3: {
    borderRadius: actuatedNormalizeModerateScale(12),
    backgroundColor: colors._FAE9DC,
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(64),
    paddingLeft:actuatedNormalizeWidth(12),
    paddingRight:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(12), 
    width:actuatedNormalizeWidth(328),
  },
  defaultOrangeContainerStyle: {
    backgroundColor: colors.FadedBlue,
    borderRadius:actuatedNormalizeModerateScale(12),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(48),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(8),
    width:actuatedNormalizeWidth(328),
  },
  defaultOrangeTextStyle: {
    ...typography.BodyRegular3,
    color: colors.PrimaryOrange100,
    textAlign: 'center',
  },
  defaultTextStyle: {
    ...typography.BodyRegular3,
    color: colors.NeutralGrey150,
    textAlign: 'center',
  },
  imageStyle: {
    height: actuatedNormalizeHeight(20),
    width: actuatedNormalizeWidth(20),
  },
  imageStyleTipsLarge: {
    minHeight: actuatedNormalizeHeight(30),
    width: actuatedNormalizeWidth(30),
  },
  neutralContainerStyle: {
    backgroundColor: colors.FadedBlue,
    borderRadius: actuatedNormalizeModerateScale(16),
    minHeight: actuatedNormalizeHeight(32),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    paddingHorizontal:actuatedNormalizeWidth(12),
    paddingVertical:actuatedNormalizeHeight(8),
    width: actuatedNormalizeWidth(296),
  },
  neutralImageStyle: {
    height: actuatedNormalizeHeight(16),
    width: actuatedNormalizeWidth(16),
  },
  neutralTextStyle: {
    ...typography.LabelLargeMedium,
    color: colors.PrimaryOrange100,
  },
  positiveInlineContainerStyle: {
    backgroundColor: colors.PastelGreen100,
    borderRadius: actuatedNormalizeModerateScale(16),
    minHeight: actuatedNormalizeHeight(32),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16), 
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(8),
    width: actuatedNormalizeWidth(328),
  },
  positiveInlineTextStyle: {
    ...typography.LabelLargeMedium,
    color: colors.Success100,
  },
  positiveLargeContainerStyle: {
    backgroundColor: colors.PastelGreen100,
    borderRadius: actuatedNormalizeModerateScale(16),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(40),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(12),
    width: actuatedNormalizeWidth(328),
  },
  positiveSmallContainerStyle: {
    backgroundColor: colors.PastelGreen100,
    borderRadius: actuatedNormalizeModerateScale(16),
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(32),
    paddingHorizontal:actuatedNormalizeWidth(12),
    paddingVertical:actuatedNormalizeWidth(8),
    width: actuatedNormalizeWidth(278),
  },
  positiveLargeTextStyle: {
    ...typography.BodyRegular3,
    color: colors.NeutralGrey130,
  },
  preConfirmationSingleContainer: {
    alignItems: 'center',
    backgroundColor: colors.LightGrayishOrangeWithOpacity40,
    borderRadius: actuatedNormalizeModerateScale(12),
    columnGap:actuatedNormalizeWidth(12),
    flexDirection: 'row',
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),
    minHeight: actuatedNormalizeHeight(56),
    minWidth: actuatedNormalizeWidth(328),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(12),
  },
  preCondSingleTextStyle: {
    ...typography.BodyRegular3,
    color: colors.NeutralGrey150,
  },
  textContainerStyle: {
    flex: 1,
    flexDirection: 'row',
  },
  textContainerTipsSmallStyle: {
    flex: 0.95,
    flexDirection: 'row',
  },
  textContainerStyleGeneraLInformation: {
    flex: 0.95,
    flexDirection: 'row',
  },
  textContainerStyleCustomIconMultiple: {
    flex: 1,
    flexDirection: 'row',
  },
  tipsSmallImageStyle: {
    height: actuatedNormalizeHeight(24),
    width: actuatedNormalizeWidth(24),
  },
  tipsLargeContainerStyle: {
      shadowOffset: { width: actuatedNormalizeWidth(0), height: actuatedNormalizeHeight(0), },
      shadowOpacity: 0,
      shadowRadius: actuatedNormalizeModerateScale(0),
      shadowColor: colors.TransperantColor,
  },
  tipsLargeHeaderTextStyle: {
    ...typography.BodySemiBold2,
    color: colors.NeutralGrey150,
    marginTop:actuatedNormalizeHeight(4),
    marginBottom: actuatedNormalizeHeight(4),
  },
  tipsLargeMargin:{
    marginLeft:actuatedNormalizeWidth(10),
  },
  tipsLargeTextStyle: {
    ...typography.BodyRegular3,
    color: colors.NeutralGrey120,
    marginTop: actuatedNormalizeHeight(2), 
    width:actuatedNormalizeWidth(256),
  },
  tipsLargeSubContainer: {
    borderColor:colors.LightYellowPallet,
    borderWidth:actuatedNormalizeModerateScale(1),
    elevation:0,
  },
  tipsLargeSubContainer2: {
    flexDirection: 'column',
  },
  warningTextStyle: {
    ...typography.BodyRegular3,
    color: colors.NeutralGrey120,
  },
  warningContainerStyle: {
    borderRadius: actuatedNormalizeModerateScale(16),
    backgroundColor:colors.Warning100WithOpacity10,
    justifyContent: 'center',
    marginHorizontal:actuatedNormalizeWidth(16),  
    minHeight: actuatedNormalizeHeight(32),
    paddingHorizontal:actuatedNormalizeWidth(16),
    paddingVertical:actuatedNormalizeHeight(8),
    width: actuatedNormalizeWidth(328),
  },
});
