// Sample Data for title On both sides Horizontal Scroll
export const sampleDataForBothTitlesHorizontalScroll = [
  {
    index: 0,
    header: '',
    values: ['Title','Title', 'Title','Title'],
  },
  {
    index: 1,
    header: 'Title2',
    values: [ 'Body Copy', 'Body Copy', 'Body Copy','Body Copy'],
  },
  {
    index: 2,
    header: 'Title3',
    values: [ 'Body Copy', 'Body Copy', 'Body Copy','Body Copy'],
  },
  {
    index: 3,
    header: 'Title4',
    values: [ 'Body Copy', 'Body Copy', 'Body Copy','Body Copy'],
  },
  {
    index: 4,
    header: 'Title5',
    values: [ 'Body Copy', 'Body Copy', 'Body Copy','Body Copy'],
  },
];

// Sample Data for title On both sides VerticalScroll
export const sampleDataForTitleBothSidesVerticalScroll = [
  {
    index: 0,
    header: 'Age',
    values: [
      '<=35 years',
      '75%',
      '55%',
      '35%',
      '20%',
      '15%',
      '10%',
      '75%',
      '55%',
      '35%',
    ],
  },
  {
    index: 1,
    header: 'Equity(E)',
    values: [
      '<= 35 years',
      '10%',
      '15%',
      '20%',
      '20%',
      '10%',
      '75%',
      '55%',
      '35%',
      '20%',
    ],
  },
  {
    index: 2,
    header: 'Corporate Bonds(C)',
    values: [
      '36-40 years',
      '15%',
      '30%',
      '45%',
      '60%',
      '75%',
      '75%',
      '55%',
      '35%',
      '20%',
    ],
  },
  {
    index: 3,
    header: 'Government Bonds(G',
    values: [
      '41-45 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 4,
    header: 'Body Copy3',
    values: [
      '<= 35 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 5,
    header: 'Corporate Bonds',
    values: [
      '36-40 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 6,
    header: 'Government Bonds',
    values: [
      '41-45 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 7,
    header: 'Equity',
    values: [
      '<= 35 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 8,
    header: 'Corporate Bonds',
    values: [
      '36-40 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
  {
    index: 9,
    header: 'Government Bonds',
    values: [
      '41-45 years',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
      'Body Copy3',
    ],
  },
];

// Sample Data for data table with full screen
export const sampleDataForFullScreen = [
  {
    index: 0,
    header: 'Title 1',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 1,
    header: 'Title 2',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 2,
    header: 'Title 3',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
];

// Sample Data for title On Left or data table with more rows
export const sampleDataMoreRows = [
  {
    index: 0,
    header: 'Title 1',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 1,
    header: 'Title 2',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 2,
    header: 'Title 3',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 3,
    header: 'Title 4',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 4,
    header: 'Title 5',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
];
