export const STRINGS = {
  str_closeModal: 'Ok',
  str_closeModalErr: 'Ok',
  str_defaultContentHeading: 'Abhishek Nair',
  str_defaultContentSubHeading: 'Axis Bank •••• 3523',
  str_emptyDrawer: 'Open Empty Drawers',
  str_errorDrawer: 'Open Error Drawers',
  str_errorDrawerTitle: 'Error Title',
  str_fixedDrawer: 'Open Default Drawers',
  str_fixedDrawerTitle: 'Title',
  str_headerCompText: 'Drawers',
  str_indErrContentHeading:
    'You cannot do a transaction from your UPI ID due to security reasons. Please retry after sometime',
  str_indSucContentHeading: 'Naina Gaikwad',
  str_indSucContentSubHeading: 'Bank of Baroda •••• 6171',
  str_indructoryDrawer: 'Open Introductory Drawers',
  str_mpinDrawer: 'Open MPIN Drawers',
  str_scrollableDrawers: 'Open Default Expandable Drawers',
  str_scrollableDrawerTitle: 'Modal',
  str_successDrawer: 'Open Success Drawers',
  str_successDrawerSubtitle: 'Subline',
  str_successDrawerTitle: 'Title',
  str_type2Drawer: 'Open Type 2 Drawers',
};
