export const sampleData = [
  {
    index: 0,
    header: '',
    values: ['Title', 'Title'],
  },
  {
    index: 1,
    header: 'Title 2',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 2,
    header: 'Title 3',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 3,
    header: 'Title 4',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
  {
    index: 4,
    header: 'Title 5',
    values: [
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
      'Body Copy',
    ],
  },
];
