/* eslint-disable linebreak-style */
export enum ScreensTechnical {
  AdobeODDemo='AdobeODDemo',
  AdobeTargetDemo='AdobeTargetDemo',
  AdobeTargetDemoAndroid='AdobeTargetDemoAndroid',
  AnalyticalInvokerDemo = "AnalyticalInvokerDemo",
  ApiManagerDemo = 'ApiManagerDemo',
  AndroidEncryptionDecryptionDemo = "AndroidEncryptionDecryptionDemo",
  BaseServiceDemo = 'BaseServiceDemo',
  CDNInvocationDemo = 'CDNInvocationDemo',
  DeviceBindingDemo = 'DeviceBindingDemo',
  DialerDemo = 'DialerDemo',
  ExceptionErrorHandlingDemo = 'ExceptionErrorHandlingDemo',
  EncryptionDecryptionDemo = 'EncryptionDecryptionDemo',
  EventRegisterDemo = 'EventRegisterDemo',
  ErrorMessagesNativeDemo = 'ErrorMessagesNativeDemo',
  ErrorMessagesNative = 'ErrorMessagesNative',
  FileManagerDemo = 'FileManagerDemo',
  GlobalHeaderDemo = "GlobalHeaderDemo",
  HtmlParseDemo="HtmlParseDemo",
  NetworkManagerDemo = "NetworkManagerDemo",
  PersistentStorageDemo = 'PersistentStorageDemo',
  ShareTrayDemo = 'ShareTrayDemo',
  UCJUrlDemo='UCJUrlDemo',
  UCJRelationManagerDemo = 'UCJRelationManagerDemo',
  ValidationDemo = "ValidationDemo",
  WebViewDemo = 'WebViewDemo',
  DisableScreenshotDemo='DisableScreenshotDemo',
  AnalyticalInvokerIOSDemo = 'AnalyticalInvokerIOSDemo',
  CacheManageDemo='CacheManagerDemo',
  DynatraceDemo = 'DynatraceDemo',
  TimeOutManagementDemo = 'TimeOutManagementDemo'
}


export enum TechnicalComponents {
  AdobeOD = "Adobe OD",
  AdobeTargetAndroid = 'Adobe Target Android',
  AdobeTarget = 'Adobe Target',
  AnalyticalInvoker = "AnalyticalInvoker",
  AnalyticalInvokerIOS = "AnalyticalInvoker IOS",
  ApiManager = 'API Manager',
  AndroidEncryptionDecryption = "Android Encryption Decryption",
  BaseService = 'Base Service',
  CacheManager = 'CacheManager',
  CDNInvocation = 'CDN Invocation',
  DeviceBinding = 'Device Binding',
  Dialer = 'Dialer',
  DisableScreenshot = 'Disable Screenshot',
  EventRegister = 'EventRegister',
  EncryptionDecryption = 'EncryptionDecryption',
  ExceptionErrorHandling = 'ExceptionErrorHandling',
  ErrorMessagesNative = "ErrorMessagesNative",
  FileManager = 'File Manager',
  GlobalHeaders = 'Global Headers',
  HtmlParse = 'HtmlParse',
  NetworkManager = 'Network Manager',
  PersistentStorage = 'PersistentStorage',
  ShareTray = 'Share Tray',
  UCJUrl = 'UCJUrl',
  UCJRelationManager = 'UCJ Relation Manager',
  Validation = 'Validation',
  WebView = 'WebView',
  Dynatrace = 'Dynatrace',
  TimeOutManagement = 'TimeOutManagement',
}
