import { UIComponent } from './UIEnums';

export const ScreenName = [
  { componentName: UIComponent.Accordions },
  { componentName: UIComponent.AccountSelectDrawer },
  { componentName: UIComponent.Avatar },
  { componentName: UIComponent.Badges },
  { componentName: UIComponent.Banners },
  { componentName: UIComponent.BasicMicroInteractions },
  { componentName: UIComponent.BreadCrumbs },
  { componentName: UIComponent.Buttons },
  { componentName: UIComponent.Cards },
  { componentName: UIComponent.Carousel },
  { componentName: UIComponent.Checkbox },
  { componentName: UIComponent.Chips },
  { componentName: UIComponent.ChoiceSelectors },
  { componentName: UIComponent.Clipboard },
  { componentName: UIComponent.Coachmarks },
  { componentName: UIComponent.DataTables },
  { componentName: UIComponent.DatePicker },
  { componentName: UIComponent.DisclaimerAndInformation },
  { componentName: UIComponent.Drawers },
  { componentName: UIComponent.Dropdown },
  { componentName: UIComponent.EmptyState },
  { componentName: UIComponent.GCA },
  { componentName: UIComponent.Graphs },
  { componentName: UIComponent.List },
  { componentName: UIComponent.MiniSuccessPage },
  { componentName: UIComponent.OneTimePassWord },
  { componentName: UIComponent.OverflowMenu },
  { componentName: UIComponent.Pagination },
  { componentName: UIComponent.PreConformation },
  { componentName: UIComponent.PrimaryNavigation },
  { componentName: UIComponent.ProgressLoader },
  { componentName: UIComponent.ProgressTracker },
  { componentName: UIComponent.RadioButton },
  { componentName: UIComponent.ScrollBarScrollList },
  // { componentName: UIComponent.SegmentControl },
  { componentName: UIComponent.Slider },
  { componentName: UIComponent.SupportDrawer },
  { componentName: UIComponent.Tabs },
  { componentName: UIComponent.TextField },
  { componentName: UIComponent.ThankYouAndErrorPage },
  { componentName: UIComponent.Tiles },
  { componentName: UIComponent.TimeLine },
  { componentName: UIComponent.TimePicker },
  { componentName: UIComponent.Toasts },
  { componentName: UIComponent.Tooltip },
  // { componentName: UIComponent.TicketView },
  { componentName: UIComponent.Shimmer },
  { componentName: UIComponent.ReadMore },
  // { componentName: UIComponent.ProcessLoader },
  //{ componentName: UIComponent.Loader },
  //{ componentName: UIComponent.ErrorAlertDrawer },
  // { componentName: UIComponent.HorizontalStackedView },
  // { componentName: UIComponent.BlurEffect },
  //{ componentName: UIComponent.CalendarAndroidNative },
  //{ componentName: UIComponent.Calendar },
  // { componentName: UIComponent.CustomStatusBar },
  //{ componentName: UIComponent.Clipboard },

  // 'File Manager',
  //'Carousel',
  //'In-App Notifications',
  //'Network Manager',
  // 'RadialSlider',
].sort(function (a: any, b: any) {
  const c = a.componentName.localeCompare(b.componentName);
  return c;
});