export const AnalyticsManagerTitle = {
  AddFavoutiteTitle : "Add - Favourite",
  AlertsWarningTitle : "Alerts - Warning",
  APIErrorTitle : "API - Error",
  BannerTrackingTitle : "Banner - Tracking",
  CtaTitle : "CTA",
  FileDownloadTitle : "File - Download",
  FormAbandonmentTitle : "Form - Abandonment",
  FormFieldErrorTitle : "Form - Field - Error",
  FormIntermediateTitle : "Form - Intermediate",
  FormStartTitle : "Form - Start",
  FormSubmissionFailureTitle : "Form - Submission - Failure",
  FormSubmissionTitle : "Form - Submission",
  InternalSearchTitle : "Internal - Search",
  NullSearchTitle : "Null - Search",
  OffersTitle : "Offers",
  PageOrScreenLoadTitle : "Page - Or - Screen - Load",
  SearchResultClickTitle : "Search - Result - Click - Tracking",
};